name: build website and start server
on: push

jobs:
  build:
    name: build website and start server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: cp packages/server/.env.example packages/server/.env
      # Run server for 5 seconds, and succeed if it didn't throw an error
      # https://stackoverflow.com/a/63643845/1268612
      - run: timeout 5 yarn start || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
